### ISSUE TITLE
tensorflow version problem

### ISSUE THREAD

**Issue by Daniel-Nabil-Artil** [maechler/nnilm#1]
I am trying to install your project on my windows 8.1
I have a problem with tensorflow version as it is only supported for python 3.5 or more and your project need 2.7 and there is no tensorflow for such version on windows
Is there any way to overcome this problem?

**Comment by maechler** [comment]
@Daniel-Nabil-Artil Unfortunately there are dependencies that are not compatible with Python 3, but the project does actually not depend on `tensorflow` directly but only over `keras`. Thus you could probably remove the `tensorflow` dependencies and use a different `keras` backend e.g. `Theano` (not sure whether that is supported on your platform): https://keras.io/backend/

I have also successfully used `plaidml` as `keras` backend to run the trainings on the GPU, it supports many GPU architectures and is also worth having a look at: https://github.com/plaidml/plaidml

If that does not work for you, it would also be possible to run it on a Linux distribution.
