### ISSUE TITLE
What is the data you use to make predictions?

### ISSUE THREAD

**Issue by chenyuliang1996** [maechler/nnilm#11]
What is the wash_disher_eco?

**Comment by maechler** [comment]
The argument `dish_washer_eco` in `python nnilm/train.py dish_washer_eco -s0 -e3` means, use the configuration from `nnilm/device_config/dish_washer_eco.json`.

In this file there is the path to the data file used. As this data files can get very large, they are not part of the Git repository.
https://github.com/maechler/nnilm/blob/762ff13b288acc0757a531da760ef9482f53fb3e/nnilm/device_config/dish_washer_eco.json#L2

The ECO dataset has been collected by the ETH and a download link can be found on this page: http://vs.inf.ethz.ch/res/show.html?what=eco-data

However you still have to convert the dataset to the required `h5` format, using the corresponding converter provided here: https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/eco

**Comment by chenyuliang1996** [comment]
Thank you very much! I will try！
