### ISSUE TITLE
Question about std

### ISSUE THREAD

**Issue by HardyChina** [maechler/nnilm#15]
Hi maechler，
Thank you for your code to help me complete my graduation project.I find in kelly's paper,target applicane's power divided by a hand-code 'maximum power demand',but in your code or kelly's response divided target's std .I am troubled by this.

**Comment by maechler** [comment]
Hi @HardyChina 

In this paper Kelly also states that they divided by the standard deviation:

```
3.6 Standardisation
In general, neural nets learn most efficiently if the input
data has zero mean. First, the mean of each sequence is
subtracted from the sequence to give each sequence a mean
of zero. Every input sequence is divided by the standard
deviation of a random sample of the training set. We do not
divide each sequence by its own standard deviation because
that would change the scaling and the scaling is likely to be
important for NILM.

-- Neural NILM: Deep Neural Networks Applied to Energy Disaggregation (https://arxiv.org/pdf/1507.06594.pdf)
```

I however did not use the standard deviation from a random sample, but the standard deviation of the entire training set. I pre-computed this value and then set it in the configuration file:

https://github.com/maechler/nnilm/blob/762ff13b288acc0757a531da760ef9482f53fb3e/nnilm/device_config/dish_washer_redd.json#L7

I guess that in the end the exact scaling value is not that important, more important is THAT you scale. The values you feed the neural network should ideally be centred around zero and close to zero (e.g. from -1 to 1).

**Comment by maechler** [comment]
@HardyChina Does this help you? Can the issue be closed?

**Comment by HardyChina** [comment]
@maechler In Kelly's paper 
'''
Targets are divided by a hand-coded ‘maximum power
demand’ for each appliance to put the target power demand into the range [0, 1].
'''
but you are right , its not import .

**Comment by HardyChina** [comment]
Thanks for your instruction. I have no more questions

**Comment by maechler** [comment]
You're welcome!
